# Generated by Django 5.2.8 on 2025-11-13 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('número_créditos', models.IntegerField()),
                ('nivel', models.CharField(max_length=100)),
                ('horas_clase_semana', models.IntegerField()),
                ('jornada', models.CharField(max_length=100)),
                ('id_docente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.docente')),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
    ]
