# Generated by Django 5.2.8 on 2025-11-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='id_docente_fk',
            new_name='docente',
        ),
        migrations.AddField(
            model_name='cursos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='curso/'),
        ),
    ]
