# Generated by Django 5.2.8 on 2025-11-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('tipo_sangre', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='docente/')),
            ],
            options={
                'db_table': 'docente',
            },
        ),
    ]
