# Generated by Django 5.2.8 on 2025-11-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='docente/'),
        ),
    ]
